# WC 2022 â€” Schema Exploration
Loads the three parquet files and documents dtypes, shapes, and key nested structures.

In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
from pathlib import Path
import json

CACHE = Path('../data/cache')
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_colwidth', 80)
pd.set_option('display.width', 120)

## 1. matches.parquet

In [2]:
matches = pd.read_parquet(CACHE / 'matches.parquet')
print('Shape:', matches.shape)
print()
print('dtypes:')
print(matches.dtypes.to_string())

Shape: (64, 55)

dtypes:
match_id                       int64
match_date                       str
kick_off                         str
home_score                     int64
away_score                     int64
match_status                     str
match_status_360                 str
last_updated                     str
last_updated_360                 str
match_week                     int64
competition_id                 int64
competition_country_name         str
competition_name                 str
competition                      str
season_id                      int64
season                           str
home_team_id                   int64
home_team                        str
home_team_gender                 str
home_team_group                  str
home_team_country_id           int64
home_team_country_name           str
away_team_id                   int64
away_team                        str
away_team_gender                 str
away_team_group                  str
away_team_country_id           int64
away_team_country_name           str
competition_stage_id           int64
competition_stage                str
stadium_id                     int64
stadium                          str
stadium_country_id             int64
stadium_country_name             str
referee_id                   float64
referee                          str
referee_country_id           float64
referee_country_name             str
home_managers                    str
away_managers                    str
home_manager_id                int64
home_manager_name                str
home_manager_nickname            str
home_manager_dob                 str
home_manager_country_id        int64
home_manager_country_name        str
away_manager_id                int64
away_manager_name                str
away_manager_nickname            str
away_manager_dob                 str
away_manager_country_id        int64
away_manager_country_name        str
data_version                     str
shot_fidelity_version            str
xy_fidelity_version              str

In [3]:
matches.head(3)

,match_id,match_date,kick_off,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,match_week,...,home_manager_country_name,away_manager_id,away_manager_name,away_manager_nickname,away_manager_dob,away_manager_country_id,away_manager_country_name,data_version,shot_fidelity_version,xy_fidelity_version
0,3857276,2022-12-01,15:00:00.000,1,2,available,available,2026-05-04T01:46:04.664252,2026-05-04T01:50:33.318123,3,...,England,1000518,Walid Regragui,NaN,1975-09-23,154,Morocco,1.1.0,2,2
1,3857271,2022-11-21,13:00:00.000,6,2,available,available,2026-05-04T01:40:47.671394,2026-05-04T01:43:30.216315,1,...,England,645,Carlos Manuel Brito Leal Queiróz,Carlos Queiroz,1953-03-01,183,Portugal,1.1.0,2,2
2,3857296,2022-12-01,15:00:00.000,0,0,available,available,2026-05-04T01:44:02.255386,2026-05-04T01:50:06.343225,3,...,Croatia,263,Roberto Martínez Montoliú,Roberto Martínez,1973-07-13,214,Spain,1.1.0,2,2

## 2. events.parquet

In [4]:
events = pd.read_parquet(CACHE / 'events.parquet')
print('Shape:', events.shape)
print()
print('dtypes:')
print(events.dtypes.to_string())

Shape: (234637, 114)

dtypes:
50_50                                object
ball_receipt_outcome                    str
ball_recovery_recovery_failure       object
block_deflection                     object
carry_end_location                   object
clearance_aerial_won                 object
clearance_body_part                     str
clearance_head                       object
clearance_left_foot                  object
clearance_other                      object
clearance_right_foot                 object
counterpress                         object
dribble_no_touch                     object
dribble_nutmeg                       object
dribble_outcome                         str
dribble_overrun                      object
duel_outcome                            str
duel_type                               str
duration                            float64
foul_committed_advantage             object
foul_committed_card                     str
foul_won_advantage                   object
foul_won_defensive                   object
goalkeeper_end_location              object
goalkeeper_outcome                      str
goalkeeper_position                     str
goalkeeper_technique                    str
goalkeeper_type                         str
id                                      str
index                                 int64
injury_stoppage_in_chain             object
interception_outcome                    str
location                             object
match_id                              int64
minute                                int64
miscontrol_aerial_won                object
off_camera                           object
out                                  object
pass_aerial_won                      object
pass_angle                          float64
pass_assisted_shot_id                   str
pass_body_part                          str
pass_cross                           object
pass_deflected                       object
pass_end_location                    object
pass_goal_assist                     object
pass_height                             str
pass_inswinging                      object
pass_length                         float64
pass_miscommunication                object
pass_outcome                            str
pass_outswinging                     object
pass_recipient                          str
pass_recipient_id                   float64
pass_shot_assist                     object
pass_switch                          object
pass_technique                          str
pass_through_ball                    object
pass_type                               str
period                                int64
play_pattern                            str
player                                  str
player_id                           float64
position                                str
possession                            int64
possession_team                         str
possession_team_id                    int64
related_events                       object
second                                int64
shot_aerial_won                      object
shot_body_part                          str
shot_end_location                    object
shot_first_time                      object
shot_freeze_frame                    object
shot_key_pass_id                        str
shot_one_on_one                      object
shot_open_goal                       object
shot_outcome                            str
shot_statsbomb_xg                   float64
shot_technique                          str
shot_type                               str
substitution_outcome                    str
substitution_outcome_id             float64
substitution_replacement                str
substitution_replacement_id         float64
tactics                              object
team                                    str
team_id                               int64
timestamp                               str
type                                    str
under_pressure                       object
block_offensive                      object
foul_committed_offensive             object
foul_committed_penalty               object
foul_committed_type                     str
foul_won_penalty                     object
goalkeeper_body_part                    str
goalkeeper_shot_saved_to_post        object
pass_cut_back                        object
shot_deflected                       object
shot_saved_to_post                   object
ball_recovery_offensive              object
pass_no_touch                        object
pass_straight                        object
shot_redirect                        object
goalkeeper_punched_out               object
bad_behaviour_card                      str
block_save_block                     object
goalkeeper_shot_saved_off_target     object
shot_saved_off_target                object
goalkeeper_success_in_play           object
shot_follows_dribble                 object
half_start_late_video_start          object
goalkeeper_lost_in_play              object

In [5]:
events.head(3)

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,shot_redirect,goalkeeper_punched_out,bad_behaviour_card,block_save_block,goalkeeper_shot_saved_off_target,shot_saved_off_target,goalkeeper_success_in_play,shot_follows_dribble,half_start_late_video_start,goalkeeper_lost_in_play
0,None,NaN,None,None,None,None,NaN,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None
1,None,NaN,None,None,None,None,NaN,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None
2,None,NaN,None,None,None,None,NaN,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None

In [6]:
print('Event type counts:')
print(events['type'].value_counts().to_string())

Event type counts:
type
Pass                 68515
Ball Receipt*        63699
Carry                53764
Pressure             16554
Ball Recovery         5821
Duel                  4389
Clearance             2684
Block                 2386
Dribble               1793
Goal Keeper           1790
Foul Committed        1775
Miscontrol            1755
Foul Won              1693
Shot                  1494
Dispossessed          1431
Interception          1371
Dribbled Past         1036
Substitution           587
Injury Stoppage        403
Half Start             286
Half End               286
Tactical Shift         243
50/50                  236
Referee Ball-Drop      162
Starting XI            128
Shield                 104
Player Off              74
Player On               74
Bad Behaviour           44
Error                   28
Offside                 26
Own Goal For             3
Own Goal Against         3

In [7]:
for etype in ['Shot', 'Pass', 'Carry', 'Pressure']:
    subset = events[events['type'] == etype]
    print(f'\n=== {etype} (n={len(subset)}) â€” sample row ===')
    row = subset.iloc[0]
    print(row.dropna().to_string())

=== Shot (n=1494) â€” sample row ===
duration                                                                                     0.397304
id                                                               473df22f-d159-4416-a5ce-62838698ea12
index                                                                                             100
location                                                                                 [96.5, 40.7]
match_id                                                                                      3857276
minute                                                                                              2
period                                                                                              1
play_pattern                                                                             Regular Play
player                                                                              Mark Anthony Kaye
player_id                                                                                     16252.0
position                                                                      Left Defensive Midfield
possession                                                                                          6
possession_team                                                                                Canada
possession_team_id                                                                               1833
related_events        [77529694-6561-4614-9484-ce4fe8049651, 9aee6c3d-786a-4be5-b554-a34b4341630e,...
second                                                                                              5
shot_body_part                                                                              Left Foot
shot_end_location                                                                       [104.1, 39.4]
shot_first_time                                                                                  True
shot_freeze_frame     [{'location': [108.6, 34.8], 'player': {'id': 9922, 'name': 'David Junior Ho...
shot_key_pass_id                                                 adb7af16-6e6c-4f23-a405-e9488608b93b
shot_outcome                                                                                  Blocked
shot_statsbomb_xg                                                                            0.038882
shot_technique                                                                                 Normal
shot_type                                                                                   Open Play
team                                                                                           Canada
team_id                                                                                          1833
timestamp                                                                                00:02:05.857
type                                                                                             Shot
under_pressure                                                                                   True

=== Pass (n=68515) â€” sample row ===
duration                                             0.83469
id                      05a57281-9295-408a-9c4f-e32d7fad4d96
index                                                      5
location                                        [61.0, 40.1]
match_id                                             3857276
minute                                                     0
pass_angle                                          3.045886
pass_body_part                                     Left Foot
pass_end_location                               [48.5, 41.3]
pass_height                                      Ground Pass
pass_length                                        12.557467
pass_recipient                                Sofyan Amrabat
pass_recipient_id                                     5234.0
pass_type                                           Kick Off
period                                                     1
play_pattern                                   From Kick Off
player                                     Youssef En-Nesyri
player_id                                             6301.0
position                                      Center Forward
possession                                                 2
possession_team                                      Morocco
possession_team_id                                       788
related_events        [1267faf9-e033-4985-925a-2f9521d63bc0]
second                                                     0
team                                                 Morocco
team_id                                                  788
timestamp                                       00:00:00.460
type                                                    Pass

=== Carry (n=53764) â€” sample row ===
carry_end_location                                                                    [48.4, 42.5]
duration                                                                                  1.120033
id                                                            fa742b13-32df-4dce-8b08-7c6ebb125d5a
index                                                                                            7
location                                                                              [48.5, 41.3]
match_id                                                                                   3857276
minute                                                                                           0
period                                                                                           1
play_pattern                                                                         From Kick Off
player                                                                              Sofyan Amrabat
player_id                                                                                   5234.0
position                                                                 Center Defensive Midfield
possession                                                                                       2
possession_team                                                                            Morocco
possession_team_id                                                                             788
related_events        [3a06bcce-1408-4a0b-be01-f6b93f142b30, 1267faf9-e033-4985-925a-2f9521d63bc0]
second                                                                                           1
team                                                                                       Morocco
team_id                                                                                        788
timestamp                                                                             00:00:01.295
type                                                                                         Carry

=== Pressure (n=16554) â€” sample row ===
duration                                                                                  1.497097
id                                                            5a7b5b9f-834d-401b-a464-b5d94ecc9b7c
index                                                                                           23
location                                                                               [76.6, 1.9]
match_id                                                                                   3857276
minute                                                                                           0
period                                                                                           1
play_pattern                                                                         From Kick Off
player                                                                                Sam Adekugbe
player_id                                                                                  29758.0
position                                                                                 Left Back
possession                                                                                       2
possession_team                                                                            Morocco
possession_team_id                                                                             788
related_events        [09886ec7-0311-4872-af90-2d51ee1cb809, 9a6a8ef5-2115-4a36-97a8-271e991b5daf]
second                                                                                          16
team                                                                                        Canada
team_id                                                                                       1833
timestamp                                                                             00:00:16.870
type                                                                                      Pressure

In [8]:
shot_cols = [c for c in events.columns if c.startswith('shot')]
print('Shot-related columns:', shot_cols)
print()
shots = events[events['type'] == 'Shot'].copy()
print(f'Total shots: {len(shots)}')
print()
for col in shot_cols:
    sample = shots[col].dropna()
    if len(sample) > 0:
        print(f'--- {col} ---')
        val = sample.iloc[0]
        if isinstance(val, dict):
            print(json.dumps(val, indent=2, default=str))
        else:
            print(repr(val))
        print()

Shot-related columns: ['shot_aerial_won', 'shot_body_part', 'shot_end_location', 'shot_first_time', 'shot_freeze_frame', 'shot_key_pass_id', 'shot_one_on_one', 'shot_open_goal', 'shot_outcome', 'shot_statsbomb_xg', 'shot_technique', 'shot_type', 'shot_deflected', 'shot_saved_to_post', 'shot_redirect', 'shot_saved_off_target', 'shot_follows_dribble']

Total shots: 1494

--- shot_aerial_won ---
True

--- shot_body_part ---
'Left Foot'

--- shot_end_location ---
array([104.1,  39.4])

--- shot_first_time ---
True

--- shot_freeze_frame ---
array([{'location': array([108.6,  34.8]), 'player': {'id': 9922, 'name': 'David Junior Hoilett'}, 'position': {'id': 19, 'name': 'Center Attacking Midfield'}, 'teammate': True},
       {'location': array([112.7,  45.5]), 'player': {'id': 16459, 'name': 'Cyle Larin'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': True},
       {'location': array([108.6,  42.5]), 'player': {'id': 12770, 'name': 'Jonathan Osorio'}, 'position': {'id': 9, 'name': 'Right Defensive Midfield'}, 'teammate': True},
       {'location': array([109.2,  27.6]), 'player': {'id': 24024, 'name': 'Tajon Buchanan'}, 'position': {'id': 16, 'name': 'Left Midfield'}, 'teammate': True},
       {'location': array([94.4, 20.6]), 'player': {'id': 29758, 'name': 'Sam Adekugbe'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': True},
       {'location': array([100.1,  49.5]), 'player': {'id': 12365, 'name': 'Alphonso Davies'}, 'position': {'id': 12, 'name': 'Right Midfield'}, 'teammate': True},
       {'location': array([89.8, 57.6]), 'player': {'id': 44703, 'name': 'Alistair Johnston'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': True},
       {'location': array([83.9, 46.1]), 'player': {'id': 11846, 'name': 'Steven de Sousa Vitoria'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': True},
       {'location': array([108.3,  47.9]), 'player': {'id': 15890, 'name': 'Noussair Mazraoui'}, 'position': {'id': 6, 'name': 'Left Back'}, 'teammate': False},
       {'location': array([112.5,  41.6]), 'player': {'id': 5234, 'name': 'Sofyan Amrabat'}, 'position': {'id': 10, 'name': 'Center Defensive Midfield'}, 'teammate': False},
       {'location': array([102.2,  46.3]), 'player': {'id': 5219, 'name': 'Romain Saïss'}, 'position': {'id': 5, 'name': 'Left Center Back'}, 'teammate': False},
       {'location': array([108.2,  36.6]), 'player': {'id': 12149, 'name': 'Nayef Aguerd'}, 'position': {'id': 3, 'name': 'Right Center Back'}, 'teammate': False},
       {'location': array([108.9,  32.3]), 'player': {'id': 5245, 'name': 'Achraf Hakimi Mouh'}, 'position': {'id': 2, 'name': 'Right Back'}, 'teammate': False},
       {'location': array([104.1,  39.3]), 'player': {'id': 46258, 'name': 'Azzedine Ounahi'}, 'position': {'id': 13, 'name': 'Right Center Midfield'}, 'teammate': False},
       {'location': array([102. ,  43.2]), 'player': {'id': 3634, 'name': 'Abdelhamid Sabiri'}, 'position': {'id': 15, 'name': 'Left Center Midfield'}, 'teammate': False},
       {'location': array([100.7,  52.2]), 'player': {'id': 3625, 'name': 'Sofiane Boufal'}, 'position': {'id': 21, 'name': 'Left Wing'}, 'teammate': False},
       {'location': array([97.1, 38.4]), 'player': {'id': 5237, 'name': 'Hakim Ziyech'}, 'position': {'id': 17, 'name': 'Right Wing'}, 'teammate': False},
       {'location': array([95.6, 41.2]), 'player': {'id': 6301, 'name': 'Youssef En-Nesyri'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'teammate': False},
       {'location': array([118.5,  39.1]), 'player': {'id': 6785, 'name': 'Yassine Bounou'}, 'position': {'id': 1, 'name': 'Goalkeeper'}, 'teammate': False}],
      dtype=object)

--- shot_key_pass_id ---
'adb7af16-6e6c-4f23-a405-e9488608b93b'

--- shot_one_on_one ---
True

--- shot_open_goal ---
True

--- shot_outcome ---
'Blocked'

--- shot_statsbomb_xg ---
np.float64(0.038882375)

--- shot_technique ---
'Normal'

--- shot_type ---
'Open Play'

--- shot_deflected ---
True

--- shot_saved_to_post ---
True

--- shot_redirect ---
True

--- shot_saved_off_target ---
True

--- shot_follows_dribble ---
True

In [9]:
xg_col = [c for c in events.columns if 'statsbomb_xg' in c or (c.startswith('shot') and 'xg' in c.lower())]
print('xG columns:', xg_col)
if xg_col:
    col = xg_col[0]
    non_null = shots[col].notna().sum()
    print(f'{col}: {non_null}/{len(shots)} shots have xG ({100*non_null/len(shots):.1f}%)')
    print('Sample values:', shots[col].dropna().head(5).tolist())

xG columns: ['shot_statsbomb_xg']
shot_statsbomb_xg: 1494/1494 shots have xG (100.0%)
Sample values: [0.038882375, 0.024477394, 0.02207015, 0.06158555, 0.27914461]

## 3. frames_360.parquet

In [10]:
frames = pd.read_parquet(CACHE / 'frames_360.parquet')
print('Shape:', frames.shape)
print()
print('dtypes:')
print(frames.dtypes.to_string())

Shape: (3084800, 7)

dtypes:
id                 str
visible_area    object
match_id         int64
teammate          bool
actor             bool
keeper            bool
location        object

In [11]:
frames.head(3)

,id,visible_area,match_id,teammate,actor,keeper,location
0,05a57281-9295-408a-9c4f-e32d7fad4d96,"[19.844310548189934, 80.0, 47.232216164843265, 0.0, 74.19741716683136, 0.0, ...",3857276,True,False,False,"[30.816379294678747, 49.38221011519904]"
1,05a57281-9295-408a-9c4f-e32d7fad4d96,"[19.844310548189934, 80.0, 47.232216164843265, 0.0, 74.19741716683136, 0.0, ...",3857276,True,False,False,"[38.59223286042586, 65.062929757288]"
2,05a57281-9295-408a-9c4f-e32d7fad4d96,"[19.844310548189934, 80.0, 47.232216164843265, 0.0, 74.19741716683136, 0.0, ...",3857276,True,False,False,"[48.38151101746609, 39.35562068791638]"

In [12]:
sample_id = frames['id'].iloc[0]
event_rows = frames[frames['id'] == sample_id]
print(f'event_uuid: {sample_id}')
print(f'visible_area: {event_rows["visible_area"].iloc[0]}')
print(f'Number of player entries in freeze_frame: {len(event_rows)}')
print()
print('Freeze frame player entries:')
print(event_rows[['teammate', 'actor', 'keeper', 'location']].to_string())

event_uuid: 05a57281-9295-408a-9c4f-e32d7fad4d96
visible_area: [ 19.84431055  80.          47.23221616   0.          74.19741717
   0.         101.85984466  80.          19.84431055  80.        ]
Number of player entries in freeze_frame: 18

Freeze frame player entries:
    teammate  actor  keeper                                 location
0       True  False   False  [30.816379294678747, 49.38221011519904]
1       True  False   False     [38.59223286042586, 65.062929757288]
2       True  False   False   [48.38151101746609, 39.35562068791638]
3       True  False   False  [56.47641107276629, 24.244798746220276]
4       True  False   False  [59.96811823850585, 11.268789077326488]
5       True  False   False   [60.38939438393986, 55.99777422890158]
6      False  False   False      [60.771255819687, 49.4155761008294]
7       True   True   False               [61.0, 40.099998474121094]
8      False  False   False   [61.06824920399342, 28.75071510493521]
9      False  False   False  [61.09961426590611, 13.127882474068514]
10      True  False   False   [61.51288180935874, 76.73595783654682]
11     False  False   False   [63.79365203563066, 57.96612800838837]
12     False  False   False   [68.74497828808629, 32.75660102724157]
13     False  False   False   [69.20329998208689, 46.01479115077606]
14     False  False   False  [71.74462205464945, 18.714596676079523]
15     False  False   False   [77.05125323611682, 62.37858198922915]
16     False  False   False    [78.7693560830433, 46.88702085361324]
17     False  False   False   [78.92557672214772, 34.60703729660807]

In [13]:
frame_ids = set(frames['id'].unique())
event_ids = set(events['id'].unique())
overlap = frame_ids & event_ids
print(f'Unique event IDs in frames_360: {len(frame_ids)}')
print(f'Unique event IDs in events:     {len(event_ids)}')
print(f'Overlap (join key works):       {len(overlap)}')
print(f'Coverage: {100*len(overlap)/len(frame_ids):.1f}% of frame events have a matching event row')

Unique event IDs in frames_360: 203882
Unique event IDs in events:     234637
Overlap (join key works):       203882
Coverage: 100.0% of frame events have a matching event row

In [14]:
print("=== Pitch coordinate system ===")
import numpy as np
locs = events["location"].dropna()
def extract_xy(v):
    if isinstance(v, (list, np.ndarray)) and len(v) >= 2:
        return float(v[0]), float(v[1])
    return None, None
xs = locs.apply(lambda v: extract_xy(v)[0]).dropna()
ys = locs.apply(lambda v: extract_xy(v)[1]).dropna()
print(f"x range: {xs.min():.1f} - {xs.max():.1f}")
print(f"y range: {ys.min():.1f} - {ys.max():.1f}")

shot_locs = events[events["type"] == "Shot"]["location"].dropna()
shot_xs = shot_locs.apply(lambda v: extract_xy(v)[0]).dropna()
print(f"\nShot x range (should cluster near 120): {shot_xs.min():.1f} - {shot_xs.max():.1f}")
print(f"Shot x median: {shot_xs.median():.1f}")

=== Pitch coordinate system ===

x range: 0.1 - 120.0
y range: 0.1 - 80.0

Shot x range (should cluster near 120): 59.0 - 120.0
Shot x median: 106.4

In [15]:
print('=== Sample matches row (JSON) ===')
print(matches.iloc[0].to_json(indent=2, default_handler=str))
print()
print('=== Sample Shot event row (JSON) ===')
shot_row = events[events['type']=='Shot'].iloc[0].dropna()
print(shot_row.to_json(indent=2, default_handler=str))

=== Sample matches row (JSON) ===
{
  "match_id":3857276,
  "match_date":"2022-12-01",
  "kick_off":"15:00:00.000",
  "home_score":1,
  "away_score":2,
  "match_status":"available",
  "match_status_360":"available",
  "last_updated":"2026-05-04T01:46:04.664252",
  "last_updated_360":"2026-05-04T01:50:33.318123",
  "match_week":3,
  "competition_id":43,
  "competition_country_name":"International",
  "competition_name":"FIFA World Cup",
  "competition":"International - FIFA World Cup",
  "season_id":106,
  "season":"2022",
  "home_team_id":1833,
  "home_team":"Canada",
  "home_team_gender":"male",
  "home_team_group":"F",
  "home_team_country_id":40,
  "home_team_country_name":"Canada",
  "away_team_id":788,
  "away_team":"Morocco",
  "away_team_gender":"male",
  "away_team_group":null,
  "away_team_country_id":154,
  "away_team_country_name":"Morocco",
  "competition_stage_id":10,
  "competition_stage":"Group Stage",
  "stadium_id":1000838,
  "stadium":"Al Thumama Stadium",
  "stadium_country_id":185,
  "stadium_country_name":"Qatar",
  "referee_id":2638.0,
  "referee":"Raphael Claus",
  "referee_country_id":31.0,
  "referee_country_name":"Brazil",
  "home_managers":"John Herdman",
  "away_managers":"Walid Regragui",
  "home_manager_id":4435,
  "home_manager_name":"John Herdman",
  "home_manager_nickname":null,
  "home_manager_dob":"1975-07-19",
  "home_manager_country_id":68,
  "home_manager_country_name":"England",
  "away_manager_id":1000518,
  "away_manager_name":"Walid Regragui",
  "away_manager_nickname":null,
  "away_manager_dob":"1975-09-23",
  "away_manager_country_id":154,
  "away_manager_country_name":"Morocco",
  "data_version":"1.1.0",
  "shot_fidelity_version":"2",
  "xy_fidelity_version":"2"
}

=== Sample Shot event row (JSON) ===
{
  "duration":0.397304,
  "id":"473df22f-d159-4416-a5ce-62838698ea12",
  "index":100,
  "location":[
    96.5,
    40.7
  ],
  "match_id":3857276,
  "minute":2,
  "period":1,
  "play_pattern":"Regular Play",
  "player":"Mark Anthony Kaye",
  "player_id":16252.0,
  "position":"Left Defensive Midfield",
  "possession":6,
  "possession_team":"Canada",
  "possession_team_id":1833,
  "related_events":[
    "77529694-6561-4614-9484-ce4fe8049651",
    "9aee6c3d-786a-4be5-b554-a34b4341630e",
    "a1952ce5-37f9-4e17-b792-f8c486714f2c"
  ],
  "second":5,
  "shot_body_part":"Left Foot",
  "shot_end_location":[
    104.1,
    39.4
  ],
  "shot_first_time":true,
  "shot_freeze_frame":[
    {
      "location":[
        108.6,
        34.8
      ],
      "player":{
        "id":9922,
        "name":"David Junior Hoilett"
      },
      "position":{
        "id":19,
        "name":"Center Attacking Midfield"
      },
      "teammate":true
    },
    {
      "location":[
        112.7,
        45.5
      ],
      "player":{
        "id":16459,
        "name":"Cyle Larin"
      },
      "position":{
        "id":23,
        "name":"Center Forward"
      },
      "teammate":true
    },
    {
      "location":[
        108.6,
        42.5
      ],
      "player":{
        "id":12770,
        "name":"Jonathan Osorio"
      },
      "position":{
        "id":9,
        "name":"Right Defensive Midfield"
      },
      "teammate":true
    },
    {
      "location":[
        109.2,
        27.6
      ],
      "player":{
        "id":24024,
        "name":"Tajon Buchanan"
      },
      "position":{
        "id":16,
        "name":"Left Midfield"
      },
      "teammate":true
    },
    {
      "location":[
        94.4,
        20.6
      ],
      "player":{
        "id":29758,
        "name":"Sam Adekugbe"
      },
      "position":{
        "id":6,
        "name":"Left Back"
      },
      "teammate":true
    },
    {
      "location":[
        100.1,
        49.5
      ],
      "player":{
        "id":12365,
        "name":"Alphonso Davies"
      },
      "position":{
        "id":12,
        "name":"Right Midfield"
      },
      "teammate":true
    },
    {
      "location":[
        89.8,
        57.6
      ],
      "player":{
        "id":44703,
        "name":"Alistair Johnston"
      },
      "position":{
        "id":2,
        "name":"Right Back"
      },
      "teammate":true
    },
    {
      "location":[
        83.9,
        46.1
      ],
      "player":{
        "id":11846,
        "name":"Steven de Sousa Vitoria"
      },
      "position":{
        "id":3,
        "name":"Right Center Back"
      },
      "teammate":true
    },
    {
      "location":[
        108.3,
        47.9
      ],
      "player":{
        "id":15890,
        "name":"Noussair Mazraoui"
      },
      "position":{
        "id":6,
        "name":"Left Back"
      },
      "teammate":false
    },
    {
      "location":[
        112.5,
        41.6
      ],
      "player":{
        "id":5234,
        "name":"Sofyan Amrabat"
      },
      "position":{
        "id":10,
        "name":"Center Defensive Midfield"
      },
      "teammate":false
    },
    {
      "location":[
        102.2,
        46.3
      ],
      "player":{
        "id":5219,
        "name":"Romain Sa\u00efss"
      },
      "position":{
        "id":5,
        "name":"Left Center Back"
      },
      "teammate":false
    },
    {
      "location":[
        108.2,
        36.6
      ],
      "player":{
        "id":12149,
        "name":"Nayef Aguerd"
      },
      "position":{
        "id":3,
        "name":"Right Center Back"
      },
      "teammate":false
    },
    {
      "location":[
        108.9,
        32.3
      ],
      "player":{
        "id":5245,
        "name":"Achraf Hakimi Mouh"
      },
      "position":{
        "id":2,
        "name":"Right Back"
      },
      "teammate":false
    },
    {
      "location":[
        104.1,
        39.3
      ],
      "player":{
        "id":46258,
        "name":"Azzedine Ounahi"
      },
      "position":{
        "id":13,
        "name":"Right Center Midfield"
      },
      "teammate":false
    },
    {
      "location":[
        102.0,
        43.2
      ],
      "player":{
        "id":3634,
        "name":"Abdelhamid Sabiri"
      },
      "position":{
        "id":15,
        "name":"Left Center Midfield"
      },
      "teammate":false
    },
    {
      "location":[
        100.7,
        52.2
      ],
      "player":{
        "id":3625,
        "name":"Sofiane Boufal"
      },
      "position":{
        "id":21,
        "name":"Left Wing"
      },
      "teammate":false
    },
    {
      "location":[
        97.1,
        38.4
      ],
      "player":{
        "id":5237,
        "name":"Hakim Ziyech"
      },
      "position":{
        "id":17,
        "name":"Right Wing"
      },
      "teammate":false
    },
    {
      "location":[
        95.6,
        41.2
      ],
      "player":{
        "id":6301,
        "name":"Youssef En-Nesyri"
      },
      "position":{
        "id":23,
        "name":"Center Forward"
      },
      "teammate":false
    },
    {
      "location":[
        118.5,
        39.1
      ],
      "player":{
        "id":6785,
        "name":"Yassine Bounou"
      },
      "position":{
        "id":1,
        "name":"Goalkeeper"
      },
      "teammate":false
    }
  ],
  "shot_key_pass_id":"adb7af16-6e6c-4f23-a405-e9488608b93b",
  "shot_outcome":"Blocked",
  "shot_statsbomb_xg":0.038882375,
  "shot_technique":"Normal",
  "shot_type":"Open Play",
  "team":"Canada",
  "team_id":1833,
  "timestamp":"00:02:05.857",
  "type":"Shot",
  "under_pressure":true
}

In [16]:
print('=== Sample frames_360 event (JSON â€” first 3 player rows) ===')
sample = frames[frames['id'] == sample_id].head(3)
print(sample.to_json(orient='records', indent=2, default_handler=str))

=== Sample frames_360 event (JSON â€” first 3 player rows) ===
[
  {
    "id":"05a57281-9295-408a-9c4f-e32d7fad4d96",
    "visible_area":[
      19.8443105482,
      80.0,
      47.2322161648,
      0.0,
      74.1974171668,
      0.0,
      101.8598446598,
      80.0,
      19.8443105482,
      80.0
    ],
    "match_id":3857276,
    "teammate":true,
    "actor":false,
    "keeper":false,
    "location":[
      30.8163792947,
      49.3822101152
    ]
  },
  {
    "id":"05a57281-9295-408a-9c4f-e32d7fad4d96",
    "visible_area":[
      19.8443105482,
      80.0,
      47.2322161648,
      0.0,
      74.1974171668,
      0.0,
      101.8598446598,
      80.0,
      19.8443105482,
      80.0
    ],
    "match_id":3857276,
    "teammate":true,
    "actor":false,
    "keeper":false,
    "location":[
      38.5922328604,
      65.0629297573
    ]
  },
  {
    "id":"05a57281-9295-408a-9c4f-e32d7fad4d96",
    "visible_area":[
      19.8443105482,
      80.0,
      47.2322161648,
      0.0,
      74.1974171668,
      0.0,
      101.8598446598,
      80.0,
      19.8443105482,
      80.0
    ],
    "match_id":3857276,
    "teammate":true,
    "actor":false,
    "keeper":false,
    "location":[
      48.3815110175,
      39.3556206879
    ]
  }
]